### ISSUE TITLE
source xcplanner

### ISSUE THREAD

**Issue by nbald** [vicb/flyxc#1]
Salut

Est-ce que tu utilises le code XCPlanner de Tom Payne ou est-ce que tu l'as réécrit from scratch ?

**Comment by vicb** [comment]
Il y a un tout petit peu de code commun mais la grande majorite a ete re-ecrite mais pas forcement from scracth:
- le calcul des secteurs FAI provient de XCSoar,
- l'optimisation du parcours provient de maxxc (de Tom egalement).
