### ISSUE TITLE
Airspace colour for RAZ

### ISSUE THREAD

**Issue by John14146** [vicb/flyxc#101]
As mentioned in the MATZ airspace issue, RAZ in the UK show red.
This is due to them been marked as Class D, not G in the OpenAPI data. 

OpenAPI admin have stated:
http://www.openaip.net/node/2885580
"Our download file contains the RAZ as RMZ type inline with the original source file. So this is more a styling problem of our map. Since the current map style does not receive updates any more, this will not be fixed in the current map. Please see https://staging.openaip.net for a new version of our map."

RAZ= Radio Advisory Zone - Class G
RMZ = Radio Mandatory Zone - Class D
Unfortunately the two are combined in the old map style.

So i guess the only solution for this problem is to either manually edit the OpenAPI data or use the new version of OpenAPI data?

![Screenshot 2021-05-15 113601](https://user-images.githubusercontent.com/83701589/118357645-2e71ab80-b573-11eb-84c9-0d336aadb68f.png)

**Comment by vicb** [comment]
Could you please add more details on what zone is affected ? (location / name of the zone).

The color on flyxc only depends on the class (G vs D) and have nothing to do with the color on openaip.

**Comment by John14146** [comment]
Yes, i have opened a thread with OpenAPI to change the class, but the old data cannot be changed. They are waiting for a new version of the website. http://www.openaip.net/node/2885580

Here is the location for the UK RAZ - Cambridge

![Screenshot 2021-05-17 200900](https://user-images.githubusercontent.com/83701589/118543329-0d17e780-b74c-11eb-8150-8291f8febc47.png)

**Comment by vicb** [comment]
What I understand from 

> Since the current map style does not receive updates anymore, this will not be fixed in the current map. Please see https://staging.openaip.net for a new version of our map.

is not that any data is going is change but only the styles are going to be updated on the new site.

Again, openaip own styles have nothing to do with flyxc.

So if there is a data issue is should be fixed and this is independent of the styles.

Does this make sense ?
What are the next steps ?

**Comment by John14146** [comment]
Correct.
In the current OpenAIP map style RAZ and RMZ and grouped in the same style, so cannot be split into Class D & G. It needs the new style to be split so the RAZ can be changed to class G. The admin has stated this.

But i cannot edit the new styles on OpenAPI. Are they still under development so users can update them? I have no answer from OpenAPI abut this.

**Comment by vicb** [comment]
> In the current OpenAIP map style RAZ and RMZ and grouped in the same style, so cannot be split into Class D & G.

That is not my understanding.

I believe that OpenAIP files define the class (D/G) and the style is derived from it.
I think what needs to be checked is if the classes in the file are correct.

**Comment by John14146** [comment]
I asked that question on API forum and recived this answer:

"Our download file contains the RAZ as RMZ type inline with the original source file. So this is more a styling problem of our map. Since the current map style does not receive updates anymore, this will not be fixed in the current map. Please see https://staging.openaip.net for a new version of our map."

 http://www.openaip.net/node/2885580
 
 I do not know what to do?

**Comment by vicb** [comment]
Here is the OpenAip definition for the RAZ:

```
<ASP CATEGORY="RMZ">
  <VERSION>a1cb6a15926c3e5ba7cfaf73c90102c7b0287338</VERSION>
  <ID>348043</ID>
  <COUNTRY>GB</COUNTRY>
  <NAME>CAMBRIDGE RAZ 120.965</NAME>
  <ALTLIMIT_TOP REFERENCE="STD">
    <ALT UNIT="FL">100</ALT>
  </ALTLIMIT_TOP>
  <ALTLIMIT_BOTTOM REFERENCE="GND">
    <ALT UNIT="F">0</ALT>
  </ALTLIMIT_BOTTOM>
  <GEOMETRY>
    <POLYGON>[...]</POLYGON>
  </GEOMETRY>
</ASP>
```

So I guess this should be changed for a class G, right ?

**Comment by John14146** [comment]
No, Because a RMZ is Class D, but they have incorrectly put a RAZ into that definition. 

They say this can be corrected in the new style. 

![Screenshot 2021-05-21 201538](https://user-images.githubusercontent.com/83701589/119187506-5b412980-ba71-11eb-8ba6-f985c5a2c4c2.png)

**Comment by vicb** [comment]
I'll change the type of that zone from RMZ to RAZ (and then from PROHIBITED to RESTRICTED color) on the next AS update in flyxc.

**Comment by John14146** [comment]
Excellent! 

Hopefully OpenAPI will also change to make future updates easier.
