### ISSUE TITLE
Feature Request? Add ability to zoom to specific pilot

### ISSUE THREAD

**Issue by greggiacovelli** [vicb/flyxc#103]
Seeing everyone is fantastic! However for safety when someone is missing, or thought to be missing, it's rather difficult right now to find their last location when there is a site that has more than 5-6 people in gaggle. We don't necessarily need to filter out other pilots but at least zoom the map to their last known plot in the last 24 hrs and go from there. Could be a drop down of all active tracks or just a simple search

**Comment by vicb** [comment]
Have you try the "live tracks" menu ?
Seems like clicking on that is what you are looking for ?

**Comment by greggiacovelli** [comment]
Oh totally! I didn't realize this was a separate feature. I'm sorry. Good to know. I will close this
