### ISSUE TITLE
Paramotor XContest scoring

### ISSUE THREAD

**Issue by lardener** [vicb/flyxc#106]
Please add scoring for paramotors for xcontest:
FAI Triangle = 4 * Km
Flat Triangle = 2 * Km
Open Path = 1 * Km
Closing radius = 800m

**Comment by vicb** [comment]
Hey,
Do you have a link to those rules on xcontest.org ?

**Comment by lardener** [comment]
https://paramotors.xcontest.org/world/en/rules/

Under section 4.1 it has the closing radius and under 4.2 is the points per
track type.
