### ISSUE TITLE
Cannot inspect airspaces after zooming with mouse

### ISSUE THREAD

**Issue by jancellor** [vicb/flyxc#121]
This has recently broken. When loading the page for the first time and showing airspaces, you can click on an airspace to see its height. After zooming the map with the mouse wheel or trackpad, clicking on an airspace does nothing. Zooming by clicking on the plus/minus buttons does not cause a problem.

**Comment by vicb** [comment]
I can reproduce the issue. The "Zooming by clicking on the plus/minus buttons does not cause a problem" is helpful and give me some ideas on what could go wrong. I'll take a look shortly. Thanks.

**Comment by vicb** [comment]
This should have been fixed (via https://github.com/vicb/flyxc/commit/76f25feafeb75cb6ac09f5745ae78a97382e6568) and will be online in ~30mn.

**Comment by jancellor** [comment]
Great, thanks
