### ISSUE TITLE
Update French airspaces

### ISSUE THREAD

**Issue by Xen01r** [vicb/flyxc#142]
Hi,

In France the military airspaces has been updated in April. Changes have been taken into account by openaip. Could you update the French airspaces ?

For example :

![image](https://github.com/vicb/flyxc/assets/49079590/6ea5b248-e67c-4bbe-94a5-2c6e78ca1787)
The airspace R45D has been deleted but it still visible on flyxc.app

![image](https://github.com/vicb/flyxc/assets/49079590/0106b000-0c7b-4e51-944e-f59b5d821e8b)
Same area on openaip.net the R45D has been successfully removed

**Comment by vicb** [comment]
I have just updated the airspaces, the updated airspaces should be available in ~1h.
Thx for reporting.
