### ISSUE TITLE
An airspace segment is missing from DEN airspace despite being in OpenAIP

### ISSUE THREAD

**Issue by vdshah** [vicb/flyxc#143]
An example point in this airspace segment which goes from 10k ft to 12k ft is 40.17038571662781, -105.07656844057806.  I checked the source data OpenAIP map and saw that they have the airspace correctly in there: https://www.openaip.net/map#10.68/40.1136/-104.9358 but for some reason this airspace segment is missing from flyxc.app

**Comment by vicb** [comment]
The airspaces are being revamped currently.

I am pretty busy right now so it might take a couple weeks.

Sorry for the inconvenience.

**Comment by vdshah** [comment]
Thank you! A few weeks isn't so bad :). Are there other known problems with it in other locations?

**Comment by vicb** [comment]
Not sure...
This one only seems to be a fix in OpenAIP that is not propagated.
Other known issues are about wrong classes for CTR and TMA.

**Comment by vicb** [comment]
<img width="668" alt="image" src="https://github.com/vicb/flyxc/assets/248818/867c9564-ea18-4a37-b8cc-d5c899240a15">

Is "[B] DENVER CLASS B AREA P" the missing airspace you are looking for?
If it is the case it might be because you have to change "floor below" in the airspaces menu
