### ISSUE TITLE
Feature request: additional filtering options of live tracks

### ISSUE THREAD

**Issue by andpol** [vicb/flyxc#146]
As popularity of flyxc.app has grown (as it should!), and more people are using the live tracking feature, at busy sites it can be difficult to read the map and see the people you care about. For example:
![image](https://github.com/vicb/flyxc/assets/894520/f58b2a2a-ab9f-48d5-b80b-9fc976be7ce5)

The time-based "History" filter is a good feature, but even more options could be nice. Some ideas:

1. Being able to add people to a "friends" list (saved to your account), and display only those tracks on the map.
2. Public groups that people can create/join and select for track filtering (I could see this getting pretty messing quickly though...)
3. Similar to above, but likely easier to implement + operate: country-based groups, and user's can select a "home" country for their account.

**Comment by vicb** [comment]
I added a filtering by name, see the search box at the top of the live track dialog

![image](https://github.com/vicb/flyxc/assets/248818/10e6bfee-bddc-49b8-b270-fbc3ba391dd0)
