### ISSUE TITLE
Huge bat symbols when loading KML files

### ISSUE THREAD

**Issue by mzeddd** [vicb/flyxc#149]
Hello.
It is possiblem to hide huge BAT symbol related to items from KML file?
![изображение](https://github.com/vicb/flyxc/assets/2010574/b2944a0f-547e-4314-99e4-19b9dc3d4c38)

I use KML file to show task with turnpoints and play IGC related to the task.
But last 2-3 weeks I see that you started to draw BAT symbols which cover whole screen.

**Comment by vicb** [comment]
That's a bug, thanks for reporting.

What Platform (Computer/phone/tablet) OS (Windows, Mac, Linux) and browser do you use ?

**Comment by vicb** [comment]
Also could you please send me the URL you see when loading this track, it should have `id=...`

**Comment by mzeddd** [comment]
Here is the example: 
https://flyxc.app/?&track=http://crc.team/netcat_files/1553/1553/2024.03.28_E11_640.igc_syncstart.igc&track=http://crc.team/netcat_files/1552/1552/T614_AA2_Regata_Standard.kml

**Comment by vicb** [comment]
Thanks I can reproduce the bug, I'll work on a fix.

**Comment by vicb** [comment]
This was fixed via #150, thanks again for your bug report!

**Comment by mzeddd** [comment]
Thank you very much!
