### ISSUE TITLE
Track replay. Mouse hover in timeline changes position

### ISSUE THREAD

**Issue by Murmele** [vicb/flyxc#180]
When playing a track it must be clicked on the right side on the play button. The problem is that sometimes the graph recognized the hover and then the the track starts from the end.

It would be nice if the hover will be only recognize if previously a mouse press event was in the diagram. So it can be easily paused without jumping to the end of the track.

Maybe using also the Spacebar to start and stop replaying the track?

Maybe moving the play elements and the combobox little bit up, out of the diagram?

I am trying to compile it my self but don't have yet success

**Comment by vicb** [comment]
Good idea, should be easy enough to change that
