### ISSUE TITLE
Menu is gone

### ISSUE THREAD

**Issue by pogacsa** [vicb/flyxc#187]
Hi, not sure if this is a feature or a bug, but flyxc is currently only a map, all of the menu items are gone. (Tried on my iphone, and under Windows 11 on Edge, Chrome and Firefox - same result.)

**Comment by vicb** [comment]
Just tested on
- Android Chrome
- Linux Chrome and Firefox
- Windows Chrome and Edge

And it's all working - it might be a temporary issue with the server or your connection.

**Comment by pogacsa** [comment]
![IMG_0881](https://github.com/vicb/flyxc/assets/33960791/714347fd-d441-490a-be01-8ef7f8ba40ea)
iphone Safari

**Comment by pogacsa** [comment]
On the desktop, it's now working, after switching VPN-s. It was probably that there.
