### ISSUE TITLE
Bat-Cursor Position not Following Track when using OpenTopoMap

### ISSUE THREAD

**Issue by indivisualvj** [vicb/flyxc#192]
When i choose OpenTopoMap as Map, the little Bat is not positioned along the tracklog whilst moving through the track. Also when i play the track it does not move along the tracklog. 
Works fine with Terrain & Satellite. Also does not work in the France and Spain maps.
I am using Google Chrome 123.x
OpenTopoMap
![image](https://github.com/vicb/flyxc/assets/7021685/29487499-532f-4bec-a740-719af96749d0)
Terrain
![image](https://github.com/vicb/flyxc/assets/7021685/29f399f6-9aa1-41fd-add4-40b640f8d01e)

**Comment by vicb** [comment]
Thanks for reporting.
It's a bug in the Google Maps JS API.
It should be solved soon when I migrate away from Google Maps

**Comment by vicb** [comment]
Might not be in Google Maps after all: https://jsfiddle.net/vicber/njqrdf07/6/
