### ISSUE TITLE
Close Flight

### ISSUE THREAD

**Issue by Bryfly** [vicb/flyxc#2]
I've just tried to create a triangle but when I used the "Close Flight" it fails to snap together the Start an Finish wpts.

PS. Great work by the way and thanks for what you have done.

**Comment by vicb** [comment]
"Close Flight" does not snap the end point to the start point but add an extra point at the same location of the start point to the end of the flight.

If this still doesn't work, could you please:
- Tell me what browser you use,
- Send me a screen copy before clicking "Close flight",
- Same after.

Thanks

**Comment by Bryfly** [comment]
Still have the same issue. In Chromium Fire Fox and Opera.

**Comment by Bryfly** [comment]
Found a work around.

Only put in Start and 2 outlying wpts the click Close Flight.
