### ISSUE TITLE
Strange view on different maps

### ISSUE THREAD

**Issue by mzeddd** [vicb/flyXC#325]
Hello,

Can you look at this?
There is a strange looking map when I change map from default to "Spane" or "France" and move map / zoom out a bit.

![изображение](https://github.com/user-attachments/assets/c3b26fab-d097-45e2-bc04-a1fa3827183b)
I know that tails are not available for this area, but BATs should always be under track trace.

[files.zip](https://github.com/user-attachments/files/17306068/files.zip)

**Comment by vicb** [comment]
Unfortunately that's a Google Maps API issue with custom maps :(

But flyXC should move away from that API soonish
