### ISSUE TITLE
QR Code for XCTrack

### ISSUE THREAD

**Issue by skydogbri** [vicb/flyxc#4]
Scanning the QR code to load a task into XCTrack on my phone returns 'unsupported QR data'. However it works fine from XCPlanner. I can download the flyxc task and manually open it but it would be much easier to scan it. Thanks

**Comment by vicb** [comment]
I asked the XCTrack team to support this a few weeks ago, they told me that they would support it.
I'll double check with them when it's going to be available.

**Comment by vicb** [comment]
It actually works for me on 0.9.2.1-beta
