### ISSUE TITLE
airspace the Netherlands not up to date 

### ISSUE THREAD

**Issue by marco2often** [vicb/flyxc#5]
Nice interactive map! Ans I support the request for 500 mtr increments.
My issue is that the airspace file for the Netherlands is almost 1 year outdated. Is there something I can do here?
Thanks,
Marco

**Comment by vicb** [comment]
Has there been a lot of changes ?

Airspaces come from openaip.net. Do you know if this source is up to date ?

I plan to update the airspaces in the coming weeks.

**Comment by vicb** [comment]
I have updated the Airspaces and set increments to 500m.
