### ISSUE TITLE
Open Distance has disappeared

### ISSUE THREAD

**Issue by ParaJesper** [vicb/flyxc#53]
The option to plan a route as Open Distance has disappeared. It constantly reverts back to competition triangles. Switching between different competitions sometimes showes this option however after a short while it disappeare again.

**Comment by vicb** [comment]
You can always look at the total distance (= open distance) on the left pane (and right pane).

I agree that the optimized route can mask part of the full route and make it harder to see the later.
I'll try to improve the UI.

Thanks for your feedback

**Comment by vicb** [comment]
I guess I can close this one ?

**Comment by ParaJesper** [comment]
Hi vicb, 

The Issue is that I can start plotting a route using "open distance" and suddenly (mostly after closing the route by adding the last waypoint next to the 1st waypoint) it reverts back to the FAI triangle screen. 

In the previous version there was an option like "free flight, or "open distance" which ( as an paramotor pilot) was of great use!
It would be greatly appreciated if this functionality could be implemented in your, otherwise superb, webapplication.

Thanks for the feedback and all your work.

**Comment by vicb** [comment]
Thanks for your feedback.

I'm reopening this issue. 

Until it's fixed you can still see the "open" distance to the right (and to the left)
