### ISSUE TITLE
user specified scoring

### ISSUE THREAD

**Issue by osmeras** [vicb/flyxc#82]
Hi,
instead choosing league, it should be better to allow user to set specific scoring for different disciplines
FAI closed triangle
Fai flat triangle
open distance
minimal closing distance

thanks

**Comment by vicb** [comment]
What is the use case ?

If there is a real use case and enough pilots interested in this feature I might consider implementing it.
It will not happen before I revamp the UI to make it easier and cleaner to display more info/options.

**Comment by osmeras** [comment]
Use case is various local leagues. For example Czech paragliding cup, we have scores
1. in czech lands:  Fai triangle 2.2, flat 1.8, free flight 1.0
2. in europe: FAI 1.4, flat 1.2, free 1.0
3. outside europe FAI 1.4, flat 1.2, free 0.8
It is to promote flying in localy  (500km flight in brazil is  similar lika 180km FAI in czech
Of course you can't put there all leagues so custom setting (preferably with cookie saving) will help.

**Comment by vicb** [comment]
@osmeras thanks for the explanation it makes sense.

As I told you I need to rework the UI before adding more options. So it will probably not be before a couple months.
Maybe an easy I could do it to add the CZ local rules as an option for now - they are probably the most useful ?

Do you have a link to the rules ?

**Comment by osmeras** [comment]
Do what is good and what is easy to implement depending on your free time (I am developer as well so I know time is always a issue)
Rules are in czech language here:  https://www.xcontest.org/cesko/pravidla/
google translation  https://translate.google.com/translate?sl=cs&tl=en&u=https://www.xcontest.org/cesko/pravidla/

But I don't want to waste your time, it is not a problem it is just suggestion for improvement, so fine for me, when you implement it after reworking UI

**Comment by vicb** [comment]
Thanks @osmeras.

If it is based on xcontest rules it's probably super easy to implement. Feel free to take submit a PR if you know TS.

**Comment by vicb** [comment]
Hey @osmeras I was looking this.

XContest has the concept of "close triangle" when the gap is smaller. See https://www.xcontest.org/world/en/rules/

As I understand it Czech does not have this concept and triangles are scored the same whatever the gap, is this right ?

**Comment by osmeras** [comment]
Hi, I tried to implement it, but I do not have where to test it.
I upload 2 file, one with change and one new.
We have just strict triangles with 5% closing distance. World scoring has 5% as well but 20% with lower scoring point. But we have different
[league.zip](https://github.com/vicb/flyxc/files/5584144/league.zip)

 scoring point depending on place where it was flown.
So I created 3 different "leagues", I took example of 3 UK leagues.

If you can please test test it. Thanks

**Comment by vicb** [comment]
Could you please submit a pull request instead, it would be easier to review discuss.

I have been quite bad at implementing tests for this project.
You can see an example in https://github.com/vicb/flyxc/tree/master/run/test/trackers.

The scoring code is not tested.
If you wish to add tests, that's great. If not that's not a problem.

_(I am doing much better with testing now, you'll see many more tests with my latest updates that are in flight)_

**Comment by vicb** [comment]
implemented in #84
