### ISSUE TITLE
UI: add tooltips to controls

### ISSUE THREAD

**Issue by lupus78** [vicb/flyxc#83]
just a minor idea/tip, add tooltips for each control to easier understand what that is. Maybe it's just me but a fighterjet does not remind me of airspaces :)

**Comment by vicb** [comment]
Thanks for your feedback @lupus78 

I have added tooltips in 304b9a95b038e43cc959e4245a3aa4c1d57cc073

But FYI I plan to completely rework the UI to make it more intuitive once I am done with the new live tracking features. See #76.
