### ISSUE TITLE
Airspace colour for MATZ

### ISSUE THREAD

**Issue by John14146** [vicb/flyxc#96]
In the UK, MATZ (military air traffic zone) can be flown into.

Can they show as Green, rather than red?

Thank you

![Screenshot of MATZ around ATC](https://user-images.githubusercontent.com/83701589/117126992-6fa7d580-ad93-11eb-9185-b1a932139156.jpg)

**Comment by vicb** [comment]
There was a discussion about MATZ at https://www.paraglidingforum.com/viewtopic.php?t=98185

I am using airspaces from openaip.net and they are classified as class D.

If they are not class D then someone (you ?) should work with openaip to change that and I'm happy to integrate that in flyxc after. I don't want to change the class. Having a single (and correct) source of of truth should be the way to go.

There is a forum at http://www.openaip.net/forum and they take feedback into account when there is evidence.

Thanks

**Comment by John14146** [comment]
The forum post states that: "Open AIP now has MATZ labelled as class G" - Tue Jun 09, 2020

As can been seen by the above screen shot, there are many track logs in the MATZ.

**Comment by vicb** [comment]
Comment/Create a new post on the forum pointing at this AS labelled D ?

**Comment by John14146** [comment]
...Post made on PG Forum. Awaiting reply

**Comment by vicb** [comment]
Answered there... 
I meant http://www.openaip.net/forum not pg forum :)

**Comment by John14146** [comment]
Post made at  http://www.openaip.net/node/2530702. Awaiting replay from OpenAIP admin.

**Comment by John14146** [comment]
OpenAIP admin has updated the map to Class G for MATZ.

**Comment by vicb** [comment]
Thanks a lot @John14146.

I am not sure if I'll have time to update the AS before the end of the week and I'll be AFK next week.

Should be online in ~2 weeks worse case. I'll update this bug when done.

**Comment by John14146** [comment]
Thank you very much. There is no rush. 
Thank you for your excellent planning website and keeping it up and maintained!

**Comment by vicb** [comment]
Thanks for the nice feedback.

_(I just checked and the updated file is not released yet - still shows class D. So probably in 2 weeks)_

**Comment by vicb** [comment]
@John14146 I have updated the airspaces, could you please check if everything looks good ?

Thanks for reporting the error here and to openaip.

**Comment by John14146** [comment]
Almost, not all tiles on all zoom levels have updated.
Also the RAZ around Cambridge is not Class G, this could be the OpenAPI data?

![zoom update](https://user-images.githubusercontent.com/83701589/117496623-375cee80-af6f-11eb-9807-9f4b11b6ffd7.png)

**Comment by vicb** [comment]
Could you try clearing your browser cache for the tiles that are not
updated at some zoom level. If still a pb send me the coordinates/as name.

Could you also please check if the error is on openaip side for the other
point ?

Thx

**Comment by John14146** [comment]
I checked before with no cache. The update seems to have finished now as all MATZ are displaying correctly. 

I have asked OpenAIP about the Cambridge RAZ.
