### ISSUE TITLE
Triangle Start/finish waypoint difference

### ISSUE THREAD

**Issue by John14146** [vicb/flyxc#97]
For UK XC league the first and last waypoint's of a declared triangle need to be identical. 
Even when carefully placed on top of each other they can be slightly different.

Can the points auto snap together when close to stop this mistake from happening?

![Screenshot_tri_waypoints](https://user-images.githubusercontent.com/83701589/117128830-d3330280-ad95-11eb-9db8-df44a08bfcc6.jpg)

**Comment by vicb** [comment]
Wouldn't that "Close flight" button work for your use case ?

![image](https://user-images.githubusercontent.com/248818/117178476-edb1af80-ad86-11eb-9abe-aba1c9ca7431.png)

**Comment by John14146** [comment]
Yes! I did not see this. Issue solved. 

Thank you
