### ISSUE TITLE
Unable to use app on Iphone 6

### ISSUE THREAD

**Issue by 70hch** [vicb/flyxc#99]
Hi It appears multiple people I know are unable to access this app on Iphone 6 devices.   Is this already a known issue and is there a work around.  I ask this as many paraglider pilots I know use Iphone 6 with FlySkyHy and this application complements that application well.

**Comment by vicb** [comment]
The app should work with any recent web browser.

What browser/version do you use and have you tried to update it ?

**Comment by 70hch** [comment]
Hi I have upgraded the phone software to 12.5.3 so Safari is the latest version for the iphone6. I have also downloaded google chrome version 90.0.4430.216 and it still does not work.  The request desktop page fails to work also in both browsers.  Everything works just fine on an iPhone 8.  There are no failure messages just a blank screen.  It kind of seems like the browsers are missing a plugin or I need to enable some non standard feature.  Thanks for you comments Chrome was worth a try.

**Comment by vicb** [comment]
Latest safari seems to be 14.x

That might explain why flyxc doesn't work.

If you can not update to 14.x on iPhone 6 then you want to buy a new phone ;)

Also my limited understanding of iPhone is that Chrome (or whatever browser) uses the same underlying browser as Safari, because of Apple.
